#!/usr/bin/env python2.6
# [Gedit Tool]
# Name=Execute File
# Shortcut=F5
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=nothing


import re
import os
 
current_file = os.getenv("GEDIT_CURRENT_DOCUMENT_PATH")
match = re.search('\.(py|rb|html|htm|xml|feature|md)$', current_file)
 
if match is None:
    print "The current file cannot be runned"
else:
    commands = {
        'rb': 'ruby "{0}"',
        'py': 'python "{0}"',
        'feature': 'cucumber --format pretty "{0}"',
        'browser': 'gnome-open "{0}"',
        'md': 'markdown "{0}" > "{0}.html"; gnome-open "{0}.html"',
    }
 
    extension = match.group(1)
 
    if extension in ['xml', 'html', 'htm']:
        extension = 'browser'
 
    command = commands[extension].format(current_file)
    print "Running command %s\n\n" % command
    os.system(command)
