#!/usr/bin/env python
# [Gedit Tool]
# Name=Execute File
# Shortcut=F5
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=nothing


import re
import os
 
current_file = os.getenv("GEDIT_CURRENT_DOCUMENT_PATH")
match = re.search('\.(py|rb|html|htm|xml|feature|md)$', current_file)
 
if match is None:
    print "The current file cannot be runned"
else:
    commands = {
        'rb': 'ruby "%(file)s"',
        'py': 'python "%(file)s"',
        'feature': 'cucumber --format pretty "%(file)s"',
        'browser': 'gnome-open "%(file)s"',
        'md': 'markdown "%(file)s" > "%(file)s.html"; gnome-open "%(file)s.html"',
    }
 
    extension = match.group(1)
 
    if extension in ['xml', 'html', 'htm']:
        extension = 'browser'
 
    command = commands[extension] % {'file': current_file}
    print "Running command %s\n\n" % command
    os.system(command)
